### ISSUE TITLE
Blank Installation Screen (Step 2)

### ISSUE THREAD

**Issue by bobreyes** [OS4ED/openSIS-Responsive-Design#1]
After entering the MySQL database credentials, I am faced with a blank (blue) screen.

![screenshot 2018-06-11 22 16 04](https://user-images.githubusercontent.com/2232/41237006-14f36afc-6dc5-11e8-97f0-1e165c61973e.png)

PHP max_execution_time is set to 3600. I am using PHP version 5.6.

**Comment by openSISAdmin** [comment]
Thanks for trying out openSIS. Please make sure you are installing this on a VPS or dedicated server with full write access. Also, upgrade the php to 7.x and try it out.

**Comment by bobreyes** [comment]
Hi! Upgraded and used PHP 7.1 and still the same issue. What do you mean by Full Write Access? To the folder containing openSIS installation or to the public_html folder?

**Comment by openSISAdmin** [comment]
Can you check to make sure you have read/write permission to the www folder. If you are running a Linux box, do a chmod -R 777 opensis  (assuming the folder name is opensis where the code is).

Also, did the system connect to your mysql instance? 

You can always purchase support by the hour from: https://opensis.com/support

Thanks

**Comment by prbt2016** [comment]
Hi @openSISAdmin,

Getting the same issue in Opensis version 7.3 while manual installation on many servers with PHP 7.1 as well as 7.2, After enabling error reporting (error_reporting(E_ALL); in install/Ins1.php), I get the following warnings and notices : 

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /{{path}}/{{to}}/{{opensis}}/functions/PragRepFnc.php:26) in /{{path}}/{{to}}/{{opensis}}/install/Ins1.php on line 32 
Notice: Undefined variable: err in /{{path}}/{{to}}/{{opensis}}/install/Ins1.php on line 80 
Notice: Undefined index: mod in /{{path}}/{{to}}/{{opensis}}/install/Ins1.php on line 81 
Notice: Undefined index: mod in /{{path}}/{{to}}/{{opensis}}/install/Ins1.php on line 155 
Warning: Cannot modify header information - headers already sent by (output started at /{{path}}/{{to}}/{{opensis}}/functions/PragRepFnc.php:26) in /{{path}}/{{to}}/{{opensis}}/install/Ins1.php on line 158 

What could be causing such issue?

**Comment by prbt2016** [comment]
@bobreyes Can you check and confirm that the above changes work or not on your server?

**Comment by pigeroomoo** [comment]
Has anyone solved this? The reason that I ask Is that I have exactly the same problem. openSIS does not seem to create the necessary databases and freezes at the "blue screen". The same thing happens irrespective of version type (i.e., responsive design or not0 or version history (at least back to v.6.5). Any ideas?

**Comment by khbtechservices** [comment]
A little late to the party here, but I experienced this on a fresh install of PHP 7.2 and my issue was that I needed to install the mysql mod:
`sudo apt install php7.2-mysql`

**Comment by grisales** [comment]
Same old same old... same history installing version 5.3 Multilanguage...

Blank screen in a 1Gb fresh VPS

**max_execution_time** 3600
**opensis folder** set to 777
**PHP** 7.2.24-0
**ubuntu** 18.04.6

Has anyone sorted it out?

**Comment by openSISAdmin** [comment]
> Same old same old... same history installing version 5.3 Multilanguage...
> 
> Blank screen in a 1Gb fresh VPS
> 
> **max_execution_time** 3600
> **opensis folder** set to 777
> **PHP** 7.2.24-0
> **ubuntu** 18.04.6
> 
> Has anyone sorted it out?

The old multilingual version will not work on PHP 7.  You will need an older version of PHP for that.

We are releasing a multilingual version for the new code in a few days and you will be able to download it and use it on your current VM.

Thanks

**Comment by mohammedNeo** [comment]
i have this problem wen i install the system and this a screen shout 
[https://mrkzgulfup.com/uploads/161657287441741.png](url)

**Comment by thepra** [comment]
Also here on 7.6, trying to install but stuck at blue screen and got a 500 after the Database Connection click on Save & Next
![immagine](https://user-images.githubusercontent.com/7032509/116617411-175d7780-a93e-11eb-80e2-37af48af6a8c.png)

**Comment by jameswill** [comment]
Hello,

Installed and checked OpenSis version 6.5 community edition on PHP versions 7.1-7.4. 

However after logging in to the installation via admin panel I am getting a blank screen. 

What causes this issue?. Any way to debug the same?.

Also is there any workaround code for making Opensis version 6.5 community edition to work with PHP 7.1.x to 7.4.x ?.
