### ISSUE TITLE
Schedule Report Confusion

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#101]
Users want are trying the below and getting confused (including myself).

![Screen Shot 2019-08-16 at 3 22 45 PM](https://user-images.githubusercontent.com/1091769/63143432-f1912180-c039-11e9-8da1-60f4e0a1afd3.png)

Expecting to see only the students from the selected course period above but we get many more students in there. What is the above filter if not filtering students for the selected course period?

![Screen Shot 2019-08-16 at 3 23 03 PM](https://user-images.githubusercontent.com/1091769/63143450-05d51e80-c03a-11e9-9756-262a7bbc36fc.png)

**Comment by openSISAdmin** [comment]
From your first screenshot, the system is supposed to show all the students who are scheduled to the course period Chemistry 11C. Look at your Chemistry class and see how many are really in there and tally the results. If it is incorrect, notify us here and we will look into this.

**Comment by ghachey** [comment]
Working
