### ISSUE TITLE
Can't add course to student with missing student

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#102]
We try the report to get students with missing schedule. We get the following.

<img width="1370" alt="Screen Shot 2019-08-22 at 10 31 35 AM" src="https://user-images.githubusercontent.com/1091769/63475445-97281300-c4c8-11e9-9ba9-40907944c4d1.png">

We try to complete the schedule for the first student above by clicking on it. The missing period is 4. We try to add the course period below which we don't think has a conflict yet it is not working with an error.

<img width="1479" alt="Screen Shot 2019-08-22 at 10 33 42 AM" src="https://user-images.githubusercontent.com/1091769/63475505-df473580-c4c8-11e9-8963-4b9b368fdd16.png">

To repeat just try it under school Colonia Middle School with latest dump sent aug 22 at 10:40am.

**Comment by ghachey** [comment]
Note that we did manage to schedule the student through the group schedule and selecting only that student though the above remains a bug.

**Comment by openSISAdmin** [comment]
Please try this again after refreshing the code. We put in scheduling fix and the code was committed to GH.

**Comment by ghachey** [comment]
Seems working
