### ISSUE TITLE
Taking attendance missing yesterday and today

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#103]
Seems that it is not showing attendance to be taken for yesterday. See the calendar below showing no holiday for Colonia Middle School.

![Screen Shot 2019-08-22 at 11 11 33 AM](https://user-images.githubusercontent.com/1091769/63477113-67c8d480-c4cf-11e9-8557-55d08261e744.png)

And in the missing attendance as of August 22 2019 we only see take attendance for 19 and 20 of August.

![Screen Shot 2019-08-22 at 11 10 40 AM](https://user-images.githubusercontent.com/1091769/63477310-4d432b00-c4d0-11e9-8335-cd0512eacfc0.png)

The server is hosted in the US with a different timezone but this should not make a difference.

**Comment by ghachey** [comment]
In addition, note that the system thinks today is 21 August (probably the time zone of the server). See below for today's attendance for a teacher.

<img width="1474" alt="Screen Shot 2019-08-22 at 11 32 33 AM" src="https://user-images.githubusercontent.com/1091769/63477409-b62aa300-c4d0-11e9-8ebe-51c58734d4da.png">

Can something be done here? Like a set timezone in the Preferences or something like that?

**Comment by ghachey** [comment]
Looking at missing attendance on the 23 August shows the following only.

<img width="1465" alt="Screen Shot 2019-08-23 at 9 07 46 AM" src="https://user-images.githubusercontent.com/1091769/63553256-9a350900-c585-11e9-8e94-44a140ffca0f.png">

**Comment by ghachey** [comment]
When taking attendance the system still thinks it is yesterday. See below on the 23 August.

<img width="1474" alt="Screen Shot 2019-08-23 at 9 09 54 AM" src="https://user-images.githubusercontent.com/1091769/63553436-192a4180-c586-11e9-9147-484b3275b111.png">

**Comment by openSISAdmin** [comment]
Change the server time to FSM time and all these will get fixed.

**Comment by ghachey** [comment]
I changed the timezone. Mostly good. However, I still have missing attendance days. See figure below.

![missing-missing-attendance](https://user-images.githubusercontent.com/1091769/63565561-31658500-c5b5-11e9-96f3-3e2c99d5bc29.png)

Can you ask the developers if I can simply fix it in the following.

![missing-missing-attendance2](https://user-images.githubusercontent.com/1091769/63565571-39252980-c5b5-11e9-86f1-2c34fdff31a9.png)

**Comment by openSISAdmin** [comment]
Aren't these valid missing attendances?

**Comment by ghachey** [comment]
Yes they are. But there are missing missing attendances. There should be missing attendance for 19, 20, 21, 22 of august but only two are showing. I believe I fixed it by entering missing records manually in missing_attendance table but if you can just check if there are no other further reaching consequence to fixing this missing missing attendances this way. See figure below now.

![Screen Shot 2019-08-23 at 3 32 35 PM](https://user-images.githubusercontent.com/1091769/63567035-434a2680-c5bb-11e9-9379-9d4863f12350.png)

**Comment by ghachey** [comment]
I'm closing and will open another issue that seems to be more easily reproducible
