### ISSUE TITLE
Specify Period in Course Period

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#106]
In FSM we have lots of cases where the same teacher teaches the same course in more then one periods. Can the automatically produced course period name also include the short code of the period (or the full period). Like below but it would also show when browsing the course manager for student scheduling and other relevant places if any.

<img width="1467" alt="Screen Shot 2019-08-22 at 4 04 14 PM" src="https://user-images.githubusercontent.com/1091769/63487541-6c08e800-c4f7-11e9-93ca-2d456bd3dd56.png">

**Comment by openSISAdmin** [comment]
You can put the course period identifier in the Shart Name field. If a teacher is teaching the same course for different grade levels, you can use the grade as the identifier.
