### ISSUE TITLE
Add support for Gender in filter and list column

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#108]
Some schools for some course periods assign students based on gender. It would be good to have Gender in the filter as shown below.

![Screen Shot 2019-08-23 at 10 06 46 AM](https://user-images.githubusercontent.com/1091769/63555728-c0f73d80-c58d-11e9-9f7f-8d7531edd00d.png)

And then add an additional column gender below and all other relevant places such as group student scheduling, etc.

![Screen Shot 2019-08-23 at 10 07 46 AM](https://user-images.githubusercontent.com/1091769/63555758-ed12be80-c58d-11e9-8588-686936422fe8.png)

**Comment by openSISAdmin** [comment]
Use the Advanced Search option and it has all the fields including Gender....
![image](https://user-images.githubusercontent.com/7434280/63560820-78a43500-c525-11e9-994b-eae130a6276b.png)


![image](https://user-images.githubusercontent.com/7434280/63560834-8c4f9b80-c525-11e9-8d52-c1ab37031d90.png)

**Comment by ghachey** [comment]
I don't see an advanced search link like in your image

**Comment by openSISAdmin** [comment]
Use another browser. Chrome does not show it some times. Something about javascript.
