### ISSUE TITLE
Blank page after finished installing

### ISSUE THREAD

**Issue by chazkame** [OS4ED/openSIS-Responsive-Design#112]
I copied the new master folder to my hosted server, I finally succeeded following the installations steps. (JUst when verifying the apache version, it said my server didnt have the most recent one; while it did in reality.) After I received the notification that the database was created, I got blank page. I tried going to the login page, nothing; tried to reinstall it, not working either.

**Comment by chazkame** [comment]
The last url I got has this in the end  "/index.php?modfunc=logout&ins=comp"

**Comment by XhantiMda** [comment]
Any luck with this, I have the same issue. Please assist.

**Comment by XhantiMda** [comment]
@chazkame  did you manage to solve this issue? What was your solution?

**Comment by openSISAdmin** [comment]
Please follow this article, hopefully this will fix your issue.

https://support.os4ed.com/hc/en-us/articles/115000440183-Why-do-I-see-a-blank-screen-while-installing-openSIS-

**Comment by sd44** [comment]
> The last url I got has this in the end "/index.php?modfunc=logout&ins=comp"

I had this probelm too.

https://support.os4ed.com/hc/en-us/articles/115000440183-Why-do-I-see-a-blank-screen-while-installing-openSIS- it cann't help me.
