### ISSUE TITLE
Version mismatches in documentation

### ISSUE THREAD

**Issue by innomadic** [OS4ED/openSIS-Responsive-Design#113]
[Documentation of installation](https://support.os4ed.com/hc/en-us/articles/201047836-Installation) seems to describe a Postgres backend ("LAPPStack") while linking to MySQL packages.  

Requirements are listed plainly as:

    Apache 2.4 and above
    MySQL 5.0 and above
    PHP 5.5 or 5.6

but release notes seem to suggest PHP 7.

What is the expected best practice?

**Comment by openSISAdmin** [comment]
The support portal was updated with proper versions.
