### ISSUE TITLE
Ethnicity hard coded for students.

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#116]
The ethnicity are still hard coded for students. See below:

![Screen Shot 2019-11-14 at 9 17 09 AM](https://user-images.githubusercontent.com/1091769/68860326-aed5f880-06bf-11ea-8b7a-64242f93d074.png)

And what is this where ethnicity_id > 15 clause for? Seems like looking for trouble.

Seems to work ok for users.

**Comment by ghachey** [comment]
In other words, everywhere there is an ethnicity field it should all be taken from the ethnicity table in the DB

**Comment by openSISAdmin** [comment]
This was fixed. You can refresh the code from the repository. Also, run this patch against the opensis database:

ALTER TABLE `students` CHANGE `ethnicity` `ethnicity_id` INT(11) NULL DEFAULT NULL;

DELETE FROM `ethnicity` WHERE `ethnicity`.`ethnicity_id` = 13;
DELETE FROM `ethnicity` WHERE `ethnicity`.`ethnicity_id` = 14;
DELETE FROM `ethnicity` WHERE `ethnicity`.`ethnicity_id` = 12;
DELETE FROM `ethnicity` WHERE `ethnicity`.`ethnicity_id` = 15;
