### ISSUE TITLE
Issues printing a report since updating to Chrome ver 80

### ISSUE THREAD

**Issue by jazoon** [OS4ED/openSIS-Responsive-Design#121]
One of our staff members who uses OpenSIS to generate and print reports is unable to print reports now. When the job is sent to the printer instead of it printing the report we get a blank page followed by an error page that states:

"ERROR: typecheck
OFFENDING COMMAND: setlinecap

STACK:

-savelevel-"

Another staff member who does some of the same functions was able to print the exact report without issue. We deduced the only difference being was the Chrome versions (the working one used Chrome 79 while the one that was receiving the error had updated to Chrome 80). When updating the working machine to Chrome 80 we started to receive the same exact error from that user's machine.

**Comment by openSISAdmin** [comment]
Unable to replicate.
