### ISSUE TITLE
Dashboard navigation is blank after log-in

### ISSUE THREAD

**Issue by akande111** [OS4ED/openSIS-Responsive-Design#123]
We are unable to navigate the GUI after log-in. We simply receive the attached blank screen, regardless of the browser used, and regardless of the links clicked. When a link is clicked, red "loading" gears appear as they should, then a blank page (attached) appears.

Initially we experienced the blank screen during installation, which we resolved based on others who posted previously.
![image](https://user-images.githubusercontent.com/58438813/76912390-1bd5e680-688a-11ea-91f4-d8ab82a0a9ed.png)
![image](https://user-images.githubusercontent.com/58438813/76912448-49bb2b00-688a-11ea-8b43-2fa12658453e.png)

**Comment by openSISAdmin** [comment]
Please contact support with more details and possibly a screencast so that it can be reproduced and resolved.
