### ISSUE TITLE
7.4 upgrade issue

### ISSUE THREAD

**Issue by mpx14** [OS4ED/openSIS-Responsive-Design#124]
Attempted an upgrade from 7.3 to 7.4 earlier today. It fails with can't find table 'opensis.app' in line 220.

I restored my installation back from a backup and checked but no such table existed in 7.3.

**Comment by openSISAdmin** [comment]
Upgrade issue fixed and code committed. Please retry.

**Comment by mpx14** [comment]
Works. Thanks for the prompt fix.
