### ISSUE TITLE
Report Card comments editing doesn't work if there are quotation marks in the field

### ISSUE THREAD

**Issue by mpx14** [OS4ED/openSIS-Responsive-Design#125]
Once the comment field of student_report_card_grades is populated with a comment that contains Quotation marks the php code is no longer able to escape them and users are not able to edit the comments for everyone listed on the page.

As far as I can see the SQL works and escapes them without a problem it is the front end web element that stops working as a result of the Quotation mark character it is displaying.

**Comment by openSISAdmin** [comment]
Code updated, check at your end.
