### ISSUE TITLE
7.4 upgrade breaks when opening student records

### ISSUE THREAD

**Issue by mpx14** [OS4ED/openSIS-Responsive-Design#126]
After a successful upgrade from 7.3 to current from 29 April 2020 when going to Students -> Student Info -> Searching for a student and clicking on one of the results returns the following error:

Traceback: | ../modules/students/Student.php at 1723

Additional Information: | Unknown column 's.ETHNICITY_ID' in 'field list'

**Comment by openSISAdmin** [comment]
Please run this SQL patch against your opensis database.

ALTER TABLE `students` CHANGE `ethnicity` `ethnicity_id` INT(11) NULL DEFAULT NULL;
