### ISSUE TITLE
Teacher not displayed in the "Add Course Period" page

### ISSUE THREAD

**Issue by nerrve** [OS4ED/openSIS-Responsive-Design#127]
If the teacher has 'Drop Date' specified which is greater than the current date, we should be able to see the teacher in the drop down for add course period. However, that is not happening.

I found out that the issue is related to this predicate mentioned in the query used to fetch the list of teachers.

ssr.END_DATE>='CURDATE() '

The quotation marks around the CURDATE() should not be there.

**Comment by nerrve** [comment]
This occurs in 7.4

**Comment by openSISAdmin** [comment]
Thanks for reporting. Which code page is it on? Can you provide the directory path so that we can have a developer look into this and remediate ASAP?

**Comment by openSISAdmin** [comment]
Code updated
