### ISSUE TITLE
Does the project use gettext for the translation ?

### ISSUE THREAD

**Issue by npettiaux** [OS4ED/openSIS-Responsive-Design#128]
Dear,
I am a Belgian long time free software activists and I have been recommended to see your program that looks very interesting. In Belgium we have 3 national languages = French, Dutch, German and a bunch of other not official but much used.
I was wondering how easy/difficult it would be to translate your program with the very good gettext suite of tools.
Best regards

**Comment by openSISAdmin** [comment]
Thanks for your post and email. We would like to connect with you and discuss the next steps. Please check your email.
