### ISSUE TITLE
Talos Security Advisory for OpenSIS (TALOS-2020-1072_1083)

### ISSUE THREAD

**Issue by CiscoTalos** [OS4ED/openSIS-Responsive-Design#130]
Hello, 
The Cisco Talos team found security vulnerabilities affecting OpenSIS. As this is a sensitive security issue, please mark this issue as private and/or provide an email address along with PGP to  receive advisory reports.
For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. https://tools.cisco.com/security/center/resources/vendor_vulnerability_policy.html

Please CC vulndev@cisco.com on all correspondence related to this issue.

**Comment by openSISAdmin** [comment]
Thanks for reporting getting this reviewed.

**Comment by CiscoTalos** [comment]
You're welcome. We look forward to any updates regarding fix and/or disclosure release. Thanks.

**Comment by openSISAdmin** [comment]
Can you please check this recent code to see if the vulnerability that you found was remediated?

Thanks

**Comment by CiscoTalos** [comment]
We tested and confirmed issues as fixed on 2020-08-17.  To date, we haven't received a response via the email thread. Please confirm for public disclosure. If we do not hear back, the issue will be subject to our 90 day disclosure deadline (on or after 2020-08-29)

**Comment by openSISAdmin** [comment]
Response sent via email and you have confirmed receipt. So closing this ticket.
