### ISSUE TITLE
Translate to spanish

### ISSUE THREAD

**Issue by AmericoES** [OS4ED/openSIS-Responsive-Design#132]
Greetings friends, a query there is the possibility of translating version 7.4 into Spanish, if this possibility exists, you can tell me how

**Comment by openSISAdmin** [comment]
We are going to release a multilingual version of this updated system very soon. Please check back in a few weeks.

Thanks

**Comment by openSISAdmin** [comment]
[lang_sp.zip](https://github.com/OS4ED/openSIS-Responsive-Design/files/5198440/lang_sp.zip)

Attached is the Spanish translation of all the English literals. Please look over it and correct any errors and report it. We will sincerely appreciate it.

**Comment by openSISAdmin** [comment]
Any update from you on the translation file? Does it look alright?

**Comment by arkhej** [comment]
> 
> 
> Any update from you on the translation file? Does it look alright?

Hi, I'm using the spanish translation, there are many mistakes, Please send me an email to check it.
