### ISSUE TITLE
Print Goal and Progresses Failing

### ISSUE THREAD

**Issue by nerrve** [OS4ED/openSIS-Responsive-Design#133]
I selected a single student and was trying to print the goal and progresses. However, it failed with the following error

> Date:	
> 06/07/2020 01:11:56
> Failure Notice:	
>  DB Execute Failed. 
> SQL:	SELECT ethnicity_name FROM ethnicity WHERE ethnicity_id=
> Traceback:	/app/opensis74/modules/students/GoalReport.php at 116
> Additional Information:	You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
> 

I'm using version 7.4

**Comment by openSISAdmin** [comment]
open the database in phpmyadmin and run this SQL

ALTER TABLE `students` CHANGE `ethnicity` `ethnicity_id` INT(11) NULL DEFAULT NULL;
