### ISSUE TITLE
Security Advisory for openSIS

### ISSUE THREAD

**Issue by ERNW-Vulnerability-Disclosure** [OS4ED/openSIS-Responsive-Design#134]
Hello openSIS team,

we have identified several vulnerabilities within openSIS. Could you therefore please contact us under disclosure@ernw.de to discuss the identified issues? Thank you!

**Comment by openSISAdmin** [comment]
We are working on this and will update this ticket soon.

**Comment by openSISAdmin** [comment]
We fixed the issue you reported. Please download the latest code and check it.

Thanks

**Comment by ERNW-Vulnerability-Disclosure** [comment]
I have checked that one of the issues was fixed. However, the other issue has not been fixed and also a more sever issue was introduced within the newly added code. Please see my email for further information.

**Comment by openSISAdmin** [comment]
Can you please check this recent code to see if the vulnerability that you found was remediated?

Thanks

**Comment by ERNW-Vulnerability-Disclosure** [comment]
The newly introduced severe issue has been fixed with the update. However, the original vulnerability is still unfixed. The details have been provided within an email.
