### ISSUE TITLE
Black Screen for any selection login

### ISSUE THREAD

**Issue by RickyTruong** [OS4ED/openSIS-Responsive-Design#135]
Hello,

I just completed the installation of OPENSIS 7.4, the installation process is perfect with no error. However, the problem I received after login when I click to calendar setup or any setup I get just get a blank white page.

I already setup the max executive time but no good. Any other ideas?

**Comment by openSISAdmin** [comment]
Please email your openSIS URL with admin access info to info@os4ed.com   
We will log in and review it. To remediate, we will probably need access to your server via ssh. 

Thanks

**Comment by ladzzzz123** [comment]
the solution should be posted here in github and what caused the issue rather than asking users to send the email with server login details, its open source product isnt it ?

**Comment by openSISAdmin** [comment]
This fixes most of the blank screen issue. However, there could be other reasons for which we need to do root cause analysis. 

https://support.os4ed.com/hc/en-us/articles/115000440183-Why-do-I-see-a-blank-screen-while-installing-openSIS-
