### ISSUE TITLE
Posting grade always opened

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#136]
The grade reporting seems to *always* be opened. Is this normal?

![misis-bug-1](https://user-images.githubusercontent.com/1091769/92082277-e355a500-edf6-11ea-8db3-b832db40e203.png)

When we are just in Quarter 2 (as per configuration of test system)

![misis-bug-2](https://user-images.githubusercontent.com/1091769/92082367-06805480-edf7-11ea-9636-6829d013eb1c.png)

But this is also true of Quarter 1. I can still enter grades after the grade posting ends.

**Comment by openSISAdmin** [comment]
This is not. We will test it out to see what is going on. Thanks for reporting.

**Comment by openSISAdmin** [comment]
We are unable to replicate this error. Please try after clearing your browser cache.


![grade posting 1](https://user-images.githubusercontent.com/7434280/92970523-d0714f00-f44c-11ea-8c37-8753b3fda0f4.png)

![grade posting 2](https://user-images.githubusercontent.com/7434280/92970528-d1a27c00-f44c-11ea-8519-a8488a2dfa04.png)
