### ISSUE TITLE
Group schedule doesn't work

### ISSUE THREAD

**Issue by arkhej** [OS4ED/openSIS-Responsive-Design#141]
I'm trying to add some student to courses.
->Scheduling -> Group Schedule -> Find some student  (Submit) ->  Student list -> Select some students -> Clic "Add Course to selected student" button -> Blank page with a "Try again" button.

This feature doesn't works in your demo page neither : http://demo.opensis.com/index.php

**Comment by openSISAdmin** [comment]
We checked the issue regarding Group Schedule, but we found it's working fine.
It may have happened that after selecting the students for group schedule, you have done a "blank submit" without selecting a course. In that case only it will show a blank page with Try Again button. You have to select the course and then hit "Add Course To Selected Students" button.
