### ISSUE TITLE
Marking period issue

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#152]
The system says marking periods are incomplete even though they are.

<img width="936" alt="Screen Shot 2021-02-05 at 10 08 54 AM" src="https://user-images.githubusercontent.com/1091769/106980099-8c377000-679a-11eb-9d43-c586549ba953.png">

<img width="935" alt="Screen Shot 2021-02-05 at 10 09 22 AM" src="https://user-images.githubusercontent.com/1091769/106980113-90638d80-679a-11eb-8c75-0cbce4ed9004.png">

And any attempt to save anything inside the marking period section results in the following error.

<img width="937" alt="Screen Shot 2021-02-05 at 10 09 42 AM" src="https://user-images.githubusercontent.com/1091769/106980162-a1140380-679a-11eb-9f60-2fc0202e0f8c.png">

**Comment by ghachey** [comment]
This was an issue of missing data because of a migration from old MariaDB server to new MariaDB server. Not related to openSIS.

**Comment by mpx14** [comment]
I had the same issue after an upgrade to version 9.1 and was able to resolve it by deleting and recreating the 4 database viewes using the CREATE function from the installation script. Not sure why but the upgrade process had set them incorrectly.
