### ISSUE TITLE
Marking Periods error without sorting order

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#154]
This was not happening before. But we have noticed since the rollover from last year if the sort order is not included we get the following when trying to save/adjust marking periods.

![bug1](https://user-images.githubusercontent.com/1091769/107729966-3f6d0f80-6d2d-11eb-9f7c-26d6f23726e7.jpg)

**Comment by ArnabOs4ed** [comment]
Hello @openSISAdmin  this issue is fixed. Please merge the fix.

**Comment by openSISAdmin** [comment]
This issue has been fixed and code merged.
