### ISSUE TITLE
Incorrect Spelling for "Enter" on Portal Login Screen

### ISSUE THREAD

**Issue by dgmay** [OS4ED/openSIS-Responsive-Design#161]
As of Ver7.6, Opensis responsive design has "Enter" mispelled on the portal login screen. It is currently spelled "Entrer" as in Enter Your Password. See attached image for a screenshot. 
![image](https://user-images.githubusercontent.com/33328412/113496084-13b40d80-94c4-11eb-80c1-6161b7d81af1.png)

**Comment by arykiller** [comment]
you can Correct it your self if u install it on localhost go to www director look for the OpenSIS folder
go this directory Opensis/lang/lang_en.php open this in any text editor like notepad or something more professional notepad++ or atom u can edit the spelling it's on the 15th line 

define("_enterPassword", "Entrer Password");
u can change it to 
define("_enterPassword", "Enter Password");

**Comment by openSISAdmin** [comment]
This has been fixed.
