### ISSUE TITLE
Issue on opensis installation

### ISSUE THREAD

**Issue by ITSolutionsAlgeria** [OS4ED/openSIS-Responsive-Design#163]
I have an issue when trying to install opensis 7.6, i've installed a fresh xampp installation

The issue is on the MySQL database connection step, after specifying the database connection infos (default infos), and clicking on next, i have no next step and no error showing

**Comment by openSISAdmin** [comment]
Did you try this? https://support.os4ed.com/hc/en-us/articles/115000440183-Why-do-I-see-a-blank-screen-while-installing-openSIS-

Also make sure the MySQL version is 5.7 and php 7.4.10 or below.
