### ISSUE TITLE
Can I change the admin profile picture?

### ISSUE THREAD

**Issue by pranaynidhi** [OS4ED/openSIS-Responsive-Design#164]
I am unable to change the admin profile picture..How can I do it??

**Comment by openSISAdmin** [comment]
Go to Users->Staff->Staff Info and search or hit submit. Find the admin user from the list. Click on the record and then update the photo.

![image](https://user-images.githubusercontent.com/7434280/119022857-10d78400-b96f-11eb-890a-ea0952748b58.png)
