### ISSUE TITLE
Blank screen while installation of Opensis version 7.6

### ISSUE THREAD

**Issue by jameswill** [OS4ED/openSIS-Responsive-Design#167]
Hello,

I tried to install Opensis 7.6 Community Edition on CentOS 7 using the following environment : 

Apache 2.4, MYSQL 5.7, PHP 7.4. 

However, I encountered with the following issue i.e:

After entering the database details and hitting the 'Save & Next'  button I get the following blank screen as shown below : 

![test](https://user-images.githubusercontent.com/6368036/120173801-072d0680-c222-11eb-8b2a-8bca6dc62457.png)

Is there any way or patch to resolve the same?.

**Comment by openSISAdmin** [comment]
Please read this article: https://support.os4ed.com/hc/en-us/articles/115000440183-Why-do-I-see-a-blank-screen-while-installing-openSIS-

**Comment by prbt2016** [comment]
Hello @openSISAdmin 

Have tried that solution i.e by increasing max_execution_time=3600 in php.ini. Yet no success. Still installation gets stuck on the same screen.

**Comment by jameswill** [comment]
Hello @openSISAdmin

Have tried that solution i.e by increasing max_execution_time=3600 in php.ini. Yet no success. Still installation gets stuck on the same screen.

**Comment by jameswill** [comment]
Awaiting your reply. Any update regarding the same ?. Any other solution or fix on this that I  can try?.
