### ISSUE TITLE
Data not shown in spreadsheet

### ISSUE THREAD

**Issue by mohsincrs** [OS4ED/openSIS-Responsive-Design#169]
Spreadsheet download is working and data is not shown there.

I have entered records of two students.
And the data shown is "Filter Name" in cell B1

I have attached the student info file that is downloaded and the contents of that file as a image file.

[Student Info.xls](https://github.com/OS4ED/openSIS-Responsive-Design/files/6612901/Student.Info.xls)

![student info contents](https://user-images.githubusercontent.com/85420616/121109101-8a54ea80-c828-11eb-83e4-b5cb276392d4.jpg)

For your information, it worked in older versions, but showing error in new version 7.6.

Please help me solve this issue.

**Comment by openSISAdmin** [comment]
It is not suppose to show the individual student data. The spreadsheet download will show the grid from where you download.
