### ISSUE TITLE
Some users could not created semester Marking Period for no apparent reason

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#17]
Attached screenshot. Most of the time it is working. But for some users they were consistently getting this issue. Two of those users were using Safari browser. Changing to latest Chrome seems to have fixed the problem. But this is clearly a bug.

<img width="1238" alt="screen shot 2018-07-24 at 10 04 01 am" src="https://user-images.githubusercontent.com/1091769/43109547-0d72bb36-8f33-11e8-9886-c759d7fcc631.png">

**Comment by openSISAdmin** [comment]
Tested with Firefox, Edge, Safari and Chrome, could not replicate.
