### ISSUE TITLE
Installation- openSIS Blue screen

### ISSUE THREAD

**Issue by infusedigitalbw** [OS4ED/openSIS-Responsive-Design#171]
Good Day,

I am encountering a blue screen after entering my database details and the installation hangs. Please may you assist with a solution to the problem. I have followed the steps in this document https://support.os4ed.com/hc/en-us/articles/115000440183?input_string=blue+screen+after+database, but the outcome is the same. Please can someone assist me with the solution. 

<img width="1277" alt="Screenshot 2021-06-16 at 13 45 03" src="https://user-images.githubusercontent.com/84867339/122638698-f91e2780-d0f5-11eb-88aa-b58779b80687.png">

**Comment by openSISAdmin** [comment]
Issue resolved and code committed to repo.
