### ISSUE TITLE
Validation error when teacher start date is before school year start date

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#2]
In OpenSIS classic I do not get this error as shown below. The date joined is 14 June 2018 and the (next) school year is 1 August 2018. This works.

![screen shot 2018-06-14 at 9 18 31 am](https://user-images.githubusercontent.com/1091769/41381587-38fe86b6-6fb4-11e8-84e2-df87a97276d7.png)

In the responsive I get the following error.

![screen shot 2018-06-14 at 9 22 00 am](https://user-images.githubusercontent.com/1091769/41381647-7a81a1ea-6fb4-11e8-9643-1bc1ec0960e0.png)

Which one should it be? I currently use the classic 6.5 as the "correct" behavior.

**Comment by ghachey** [comment]
As a result I can not create Course Periods with those teachers before the actual start of school year which is a major inconvenience. Should be able to create those in advanced. See below no teachers available from list yet I created my teachers.

![screen shot 2018-06-14 at 9 55 54 am](https://user-images.githubusercontent.com/1091769/41382733-3c39ef28-6fb9-11e8-9bd4-50ab16088dae.png)

**Comment by ghachey** [comment]
I see this in the OpenSIS 6.5 Classic to address this problem which is what I have temporarily done in the responsive code base for now.

![screen shot 2018-06-14 at 10 11 59 am](https://user-images.githubusercontent.com/1091769/41383254-81c8907e-6fbb-11e8-9dda-a88ab3672202.png)

**Comment by ghachey** [comment]
I see this in the OpenSIS 6.5 Classic to address this problem which is what I have temporarily done in the responsive code base for now.

![Uploading Screen Shot 2018-06-14 at 10.11.59 AM.png…]()

**Comment by openSISAdmin** [comment]
Teacher's joining date and the school start date validation has been removed
