### ISSUE TITLE
Email validator rejects .school domain

### ISSUE THREAD

**Issue by cls-registrar** [OS4ED/openSIS-Responsive-Design#26]
When adding a new student with our new domain ending in .school we get an "Please enter a valid email" message.

![opensis email problem](https://user-images.githubusercontent.com/42213555/44361987-a1ff3080-a48d-11e8-8530-54fc373ed395.jpg)

**Comment by openSISAdmin** [comment]
This email validation has been removed. Now it will accept any email address.
