### ISSUE TITLE
Student Picture Upload Issue

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#28]
I am sending you this error when upload student's picture.

![picture-upload](https://user-images.githubusercontent.com/1091769/44589171-31f2f200-a78e-11e8-9841-62c35a42ab25.png)

**Comment by openSISAdmin** [comment]
If you do a fresh installation of the system, you will not get this error. For upgrades, there might be some issues, we are working to identify and resolve those.

**Comment by somadmin** [comment]
Hello, 

I did a new installation and I am getting the following error for school logo

![logo upload 1](https://user-images.githubusercontent.com/42398090/44826980-a4bcfc80-abd6-11e8-81a1-a901c55d88e8.PNG)
![logo upload](https://user-images.githubusercontent.com/42398090/44826985-a8e91a00-abd6-11e8-91df-ccff8add5c2f.PNG)

**Comment by openSISAdmin** [comment]
This is fixed
