### ISSUE TITLE
School Information page turns red sometimes

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#3]
When I tried to update a password for users portal account I got the following. No errors and seems the password was saved but got the following.

![screen shot 2018-06-14 at 9 29 01 am](https://user-images.githubusercontent.com/1091769/41381930-90b26746-6fb5-11e8-85c2-8fc228873508.png)

**Comment by openSISAdmin** [comment]
This issue is not occurring with the new code.
