### ISSUE TITLE
Student Bulk Upload

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#30]
An extremely important feature for the adoption of this system in our context. All principals and teachers expressed a need for this feature to be willing to use the system.

This should be an excel sheet with all the minimal set of required data following a strict template for an initial student creation. All data for each record in the upload should be validated with proper error feedback to user uploaded the excel spreadsheet.

**Comment by openSISAdmin** [comment]
This utility has been created and uploaded

**Comment by somadmin** [comment]
![error](https://user-images.githubusercontent.com/42398090/45597143-3c6b6a80-b98d-11e8-8385-f19b7f4189fe.PNG)
How do you use the tool?
