### ISSUE TITLE
Group Scheduling Issue

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#31]
Another issue that came up is when participants try to do "Group Scheduling" by clicking the submit to show student list, it returns with a blank page (Attached). So for this, we will have to skip this exercise.

![group-scheduling](https://user-images.githubusercontent.com/1091769/44592791-01b05100-a798-11e8-9c36-5be689685fc3.png)

**Comment by openSISAdmin** [comment]
This issue has been resolved and code committed.
