### ISSUE TITLE
Upload tool

### ISSUE THREAD

**Issue by somadmin** [OS4ED/openSIS-Responsive-Design#32]
![error](https://user-images.githubusercontent.com/42398090/45597151-586f0c00-b98d-11e8-8ae8-ab656ec023e8.PNG)
How do you use the tool to import the data?

**Comment by openSISAdmin** [comment]
[openSIS_DIT.pdf](https://github.com/OS4ED/openSIS-Responsive-Design/files/2391483/openSIS_DIT.pdf)

Follow this user guide
