### ISSUE TITLE
Teacher Re-Assignment Date

### ISSUE THREAD

**Issue by cls-registrar** [OS4ED/openSIS-Responsive-Design#37]
There is a problem with the assign date when doing a teacher re-assignment. I enter the date using the calendar for August 28, 2018 and when it is saved it is saying August 18, 2028. I suspect it is a date format issue but I'm not an expert. In the picture I stimply entered the assign date again so you can compaire the entered format to the saved format. Thanks for the hard work you put into this!

![teacher re-assignment issue](https://user-images.githubusercontent.com/42213555/48028316-35551300-e119-11e8-9aa4-ec302fd5f225.png)

**Comment by openSISAdmin** [comment]
This is resolved and code committed.
