### ISSUE TITLE
Grades Configuration weighting only works for one course period

### ISSUE THREAD

**Issue by benny2744** [OS4ED/openSIS-Responsive-Design#38]
Teachers with multiple grade periods are only able to set weighted grades for one of the course periods. In all the other course periods, even if the "weighted grades" option is checked in configuration, when they go to add assignment types or edit assignment types, the field for setting the weight and seeing the total percentage of the weights does not show up. However, in the progress reports, the column for "Weight" shows 0%. It seems like there might be something wrong with the add assignments page.

**Comment by openSISAdmin** [comment]
This is resolved and code committed.
