### ISSUE TITLE
Password validation

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#4]
When I enter the following test password I get the feedback that it is invalid. Changing any characters turns the validation feedback into Good. Also, for some users the same password is shown as invalid while other users can have a feedback of "Good". The password validation is not working well. Also refer to #2 

![screen shot 2018-06-14 at 9 33 19 am](https://user-images.githubusercontent.com/1091769/41382054-2b251a12-6fb6-11e8-8b56-7649d8d8450f.png)

**Comment by openSISAdmin** [comment]
We have made the password validation simpler. Please provide feedback.
