### ISSUE TITLE
No students found for all courses

### ISSUE THREAD

**Issue by msimbenda** [OS4ED/openSIS-Responsive-Design#40]
Hi all

I recently started using openSIS 7.0 community edition. I went through all tutorials to from setting up school, create subject, course and course period; i also set up grade levels, grading scales and added students to a specific grade.

**To be more specific**
- I created a grade 1 level
- I created a teacher staff
- I added a student and enrolled them in grade 1
- Created semesters 1,2,3 for the FY 2018 which runs from 8th Jan to 5th Dec 2018
- Created a subject Language, Course English and course period for the teacher and course which uses the Main grading scale for marking period of Semester 3 (runs from 1st to 5th December) on a fixed schedule.

**Issue**
- On teacher's portal: Teacher cannot enter Final grades as there are no students for the course that the teacher was assigned. My logic is teacher-course assignment is done during course period setup
(HELP NEEDED).

- Student cannot see their course, schedule and Progress report as it seems they are registered for Grade 1 but no course was assigned to them.

Please help to understand the setup process or if there is anything i missed.

Below is a teacher's attempt to enter final grades.
![found0](https://user-images.githubusercontent.com/10807261/49326853-1d7a7e80-f561-11e8-8ff3-0c643cf3862a.png)

**Comment by openSISAdmin** [comment]
Looks like this is a user error. You could have missed the scheduling of students into the correct course period for the correct marking period. Also, the teacher has to be scheduled for that course period to be able to see the students.

You can purchase a-la-carte training and support by the hour from https://www.opensis.com/support

Thanks
