### ISSUE TITLE
Back to User List or Deselect Issue

### ISSUE THREAD

**Issue by hcsadmin** [OS4ED/openSIS-Responsive-Design#47]
Could you add "Back to user list" or "Deselect" button in User - Teacher Program - Take attendance?
I have to go back to home and deselect and click all the above menus again to change user.
Thank you!

![image](https://user-images.githubusercontent.com/45839624/50132967-fea01a00-02cc-11e9-824b-a922fdb15b2a.png)

**Comment by openSISAdmin** [comment]
Added and build updated
