### ISSUE TITLE
Calendar Issue

### ISSUE THREAD

**Issue by hcsadmin** [OS4ED/openSIS-Responsive-Design#48]
Hi.
I cannot modify or delete events and add a new event.
Please fix it. Thank you.
   
School Setup - Calendars
![image](https://user-images.githubusercontent.com/45839624/50264594-b3b60c00-045e-11e9-92e1-1fa16ad6e214.png)
@openSISAdmin

**Comment by openSISAdmin** [comment]
Fixed
