### ISSUE TITLE
Course period not showing

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#5]
I've created two new course periods. There are not showing under their courses (i.e. Physics) as shown below.

![screen shot 2018-06-14 at 11 42 18 am](https://user-images.githubusercontent.com/1091769/41385564-199899ba-6fc8-11e8-89ce-cf3b2678e166.png)

Yet I see then in the course Catalogue.

![screen shot 2018-06-14 at 11 43 20 am](https://user-images.githubusercontent.com/1091769/41385575-2c2b40d2-6fc8-11e8-8428-012763a10caf.png)

**Comment by ghachey** [comment]
It seems it does not show the Course Period when they are in the second semester (or quarter 3 and quarter 4). Is this normal behavior since I see it in OpenSIS 6.5 Classic? It is not to me for many reasons.

**Comment by openSISAdmin** [comment]
Yes, this is normal behavior. If you are in Quarter 1, the Course Periods for future Quarters are suppressed to make it less confusing for the user. Switch the Term from upper right corner to the desired term to view course periods for that term.
