### ISSUE TITLE
Curl not recognized

### ISSUE THREAD

**Issue by kkallsen** [OS4ED/openSIS-Responsive-Design#52]
I have installed ubuntu 18.04 LTS with Virutalmin, Apache, Mysql, PHP, Curl and etc. However the install does not recoginse my verson of curl.

curl -V
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp

I was able to edit out the curl request from the install file and the rest of the install worked fine. HELP

**Comment by mpx14** [comment]
Same, this part of the install logic didn't work for me either as it would always branch to seek a newer version than the one you have install. I had to disable it to get OpenSIS 7 installed on Debian 9 (stable, testing & unstable). It is fairly straight forward to modify the condition in install/Step1.php.

**Comment by RobbieBott** [comment]
I've got the same issue. I simply drill down into the install folder and edit the SystemCheck.php and modify the curl error to =0 instead of 1, it still shows fail but you can continue the install.

**Comment by RobbieBott** [comment]
After running this line the CURL error goes away.
sudo apt install php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip
