### ISSUE TITLE
"Assigned date cannot be blank" error message, but is not marked as required

### ISSUE THREAD

**Issue by cls-registrar** [OS4ED/openSIS-Responsive-Design#53]
When creating a new assignment I noticed the assigned date was not marked as required. I would like if this was a possibility since I like to enter the periods' assignments all at one time and then set the assigned date as I assign them. However, when I tried to save the assignment it says it can't be blank. I wish it was possible although I suspect it's not. Either way, the markings and errors should agree. Maybe a new feature could be a "save as draft" option.

![2019-01-27](https://user-images.githubusercontent.com/42213555/51814346-07e7b380-2289-11e9-8561-71adc98983fc.png)

**Comment by openSISAdmin** [comment]
Assigned date and due date both appear as required now. We can't make them save blank data this will make the system buggy.
