### ISSUE TITLE
Tab goes to Comments instead of Points

### ISSUE THREAD

**Issue by cls-registrar** [OS4ED/openSIS-Responsive-Design#54]
When entering points for one student, tab moves down the column of points, however, when tabbing to the last point box it jumps to the top of the comments column instead of the last point cell. Maybe there is a reason for this but, I don't think it does this when entering points by assignment instead of by student.

![2019-01-27 1](https://user-images.githubusercontent.com/42213555/51814634-5053a100-228a-11e9-83fa-f5bb7205cf5f.png)

**Comment by openSISAdmin** [comment]
Resolved
