### ISSUE TITLE
Import Utility Broken

### ISSUE THREAD

**Issue by RobbieBott** [OS4ED/openSIS-Responsive-Design#56]
When uploading an .xlsx file there is no option to make the one to one link.

<img width="1006" alt="screen shot 2019-02-27 at 7 20 11 am" src="https://user-images.githubusercontent.com/10303297/53493154-4cb96280-3a60-11e9-981d-1489c8c5d7aa.png">

**Comment by openSISAdmin** [comment]
This issue has been fixed. Get the updated page from /modules/tools/DataImport.php and replace it.

Also, make sure that the column names/headers in your Excel Sheet do not have any spaces. For example "first name" is incorrect. It has to be "first_name or firstname".
