### ISSUE TITLE
Cannot Add Staff

### ISSUE THREAD

**Issue by shaffiqv** [OS4ED/openSIS-Responsive-Design#58]
I cannot add staff

**Comment by openSISAdmin** [comment]
In order to troubleshoot please create a video of how you are adding staff and what error you are getting. You can then share the link in this post.

Thanks

**Comment by shaffiqv** [comment]
Hi,

Please see video here https://drive.google.com/file/d/1xvy45n__ciFV91ychRq_3Ij2Ab-Wn19o/view?usp=sharing

Specs:
PHP5.6
MySQL 5.6
Apache2.4
Windows 10

**Comment by openSISAdmin** [comment]
The Teacher you added is in the database. When searching for Staff, check the "Include Disabled Staff" switch and you will see your Teacher.

The reason the Teacher is disabled is that you did not provide openSIS access during creation. You can edit the teacher record and provide openSIS access and the Teacher will become active.
