### ISSUE TITLE
Issue with Init of Database

### ISSUE THREAD

**Issue by dutchvanderlinde** [OS4ED/openSIS-Responsive-Design#59]
![image](https://user-images.githubusercontent.com/40540813/55853229-2215fb80-5b2e-11e9-904d-ee3a6385fb68.png)
I basically just get this blank screen as soon as I hit submit on my end, no errors or anything I can find relevant.

PHP: 5.6
Server: Apache2
Proxy: nginx
Operating System: Ubuntu Linux/GNU 18 LTS

**Comment by openSISAdmin** [comment]
It's difficult to predict why it is doing so without digging deeper into your installation. Please purchase support by the hour so that we can schedule a Skype/WebEx call to see your installation and relevant permissions.

Click here to purchase: https://opensis.com/support 

Thanks

**Comment by bobreyes** [comment]
> It's difficult to predict why it is doing so without digging deeper into your installation. Please purchase support by the hour so that we can schedule a Skype/WebEx call to see your installation and relevant permissions.
> 
> Click here to purchase: https://opensis.com/support
> 
> Thanks

Can't you just give a possible solution first or which permissions to check before you sell us support? Thanks!

**Comment by openSISAdmin** [comment]
Check for read-write permission on the opensis folder. Make sure the system is connecting to the mysql database. 

Basically, make sure the pre-requisites are fulfilled.
