### ISSUE TITLE
No validation check when putting a period start date the same as the end date of pevious period

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#6]
![screen shot 2018-06-15 at 9 25 14 am](https://user-images.githubusercontent.com/1091769/41441371-0b3eecb4-707e-11e8-93e0-9337338b755e.png)

This seems to create some conflict later on when creating course periods. For example, I could not create a Homeroom Attendance course period with an error Teacher not available while the teacher only had a course period for period 1 which is right after as shown above.

**Comment by openSISAdmin** [comment]
This is not an error, but a feature. We have schools with overlapping period times. In order for Teachers to be available, you have to create periods with at least one minute break in between.

**Comment by ghachey** [comment]
I don't think you understood. This feature was actually missing! As the title of the issue states "No validation check". This means there was no validation check like there is in classic version. This was creating conflicts later on as reported. But this seems fixed in latest beta 7 release so all good.
