### ISSUE TITLE
Period time issue

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#61]
On my laptop I can no longer use the time picker when nearer the bottom of the screen. I have to type time manually.

<img width="1393" alt="Screen Shot 2019-07-03 at 7 25 39 PM" src="https://user-images.githubusercontent.com/1091769/60571980-4d705580-9dc0-11e9-9569-038a12bc3732.png">

**Comment by openSISAdmin** [comment]
Try to clear browser cache and do it again. We are unable to replicate this issue.

**Comment by ghachey** [comment]
Clearing browser cache does not fix. To reproduce set your display at the lowest resolution and add many periods.
