### ISSUE TITLE
Gender option missing from bulk import for Staff Data

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#63]
Can't find gender mapping.

<img width="1374" alt="Screen Shot 2019-07-03 at 8 49 24 PM" src="https://user-images.githubusercontent.com/1091769/60577763-bd380d80-9dcb-11e9-9727-0bf857953f4c.png">

**Comment by openSISAdmin** [comment]
The Gender option is present in the database list of fields.

![Gender field](https://user-images.githubusercontent.com/7434280/60640277-64309f80-9df4-11e9-95e5-b853f9329e66.PNG)

**Comment by openSISAdmin** [comment]
The Gender option in Staff data import is missing. So reopening the ticket.

**Comment by openSISAdmin** [comment]
Fixed and code committed.
