### ISSUE TITLE
System accepts duplicate Alternate ID

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#65]
There should be no duplicate on alternate ID. When loading the student using bulk import tool it accepts duplicate ID. (See 111124 below)

<img width="811" alt="Screen Shot 2019-07-05 at 12 31 10 PM" src="https://user-images.githubusercontent.com/1091769/60691070-99cea900-9f18-11e9-9039-b4bce5aaa334.png">

**Comment by openSISAdmin** [comment]
Fixed
