### ISSUE TITLE
Data import tool imports all student birthday incorrectly

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#66]
They seems to be imported with an offset of -1 day.

See the spreadsheet imported.

<img width="1064" alt="Screen Shot 2019-07-05 at 12 39 21 PM" src="https://user-images.githubusercontent.com/1091769/60691188-af909e00-9f19-11e9-8179-c70f2d97abb0.png">

Now check out one of the students birthdate.

<img width="1287" alt="Screen Shot 2019-07-05 at 12 40 25 PM" src="https://user-images.githubusercontent.com/1091769/60691202-c3d49b00-9f19-11e9-8929-df9c4baa292f.png">

**Comment by ghachey** [comment]
This same problem also seems present with Estimated Graduation Date and Student Enrollment Date. Probably *all* dates.

**Comment by ghachey** [comment]
It may be worth looking whether the PHP date conversion from Excel is a full timestamp. The timezone difference could be responsible for this 1 day offset.

**Comment by openSISAdmin** [comment]
Fixed and code committed.

**Comment by eskinder-mesfin** [comment]
Please help mine does not import section and grade. or show me how to import student detail with section and grade

**Comment by ghachey** [comment]
Hi @eskinder-mesfin . You need to make sure you import with the codes you have used. Say you created your grades in the system like title Grade 1 and short code G1 in your spreadsheet you need to make sure you put G1 (the short code). Same thing with sections.
