### ISSUE TITLE
Group assign student info not working

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#67]
When trying to set the Grade 1 to all students I get the following.

<img width="1281" alt="Screen Shot 2019-07-05 at 12 58 18 PM" src="https://user-images.githubusercontent.com/1091769/60691573-6a21a000-9f1c-11e9-9f3f-f17d32070a9f.png">

**Comment by openSISAdmin** [comment]
Fixed and code committed.
