### ISSUE TITLE
Missing student when taking attendance

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#69]
It seems that is when the student's enrollment info Start Date is changed the student will still not be shown when taking attendance. For example. First create student with Start Date of 4 July. Then edit to 1 July. Then assign the student to a course period that starts on the 1 July. Try to take attendance for the 1 July. The student is missing like below.

<img width="1282" alt="Screen Shot 2019-07-05 at 4 29 34 PM" src="https://user-images.githubusercontent.com/1091769/60698228-3b1a2700-9f3a-11e9-8399-04fa78113b50.png">

But take attendance for the 4 July and you will see the students.

<img width="1280" alt="Screen Shot 2019-07-05 at 4 25 50 PM" src="https://user-images.githubusercontent.com/1091769/60698248-508f5100-9f3a-11e9-95cb-d516b4f410f0.png">

Seems like a bug.

**Comment by openSISAdmin** [comment]
Fixed and code committed.
