### ISSUE TITLE
Apply to all Periods for this Course working incorrectly

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#70]
For Apply to all Periods for this Course, I would expect this to only create the same assignment in all the periods **of the same course**. Yet I see it created for all periods. For example, I Have a course Oral and Period Oral for Grade 1 in Period 1.  I enable the option as below. I did the same for another class room assignent 2.

<img width="1279" alt="Screen Shot 2019-07-05 at 6 05 43 PM" src="https://user-images.githubusercontent.com/1091769/60701381-4f185580-9f47-11e9-9009-3c730b7a0c72.png">

Those two same assignment also get created in the Homeroom attendance which is not the same course at all and undesirable.

<img width="1297" alt="Screen Shot 2019-07-05 at 6 06 20 PM" src="https://user-images.githubusercontent.com/1091769/60701433-7b33d680-9f47-11e9-9764-20e9f5967a96.png">

**Comment by openSISAdmin** [comment]
Fixed and code committed.
