### ISSUE TITLE
Missing fields on low resolution

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#71]
Missing fields to set access to system on low resolution displays. To reproduce, set your display resolution to the lowest resolution. then try creating a staff and providing openSIS access.

![low-resolution-bug-missing-access-to-system](https://user-images.githubusercontent.com/1091769/60850900-60ae7580-a245-11e9-89ac-8ac021cfa027.PNG)

One non-ideal fix is to zoom out using the browser.

**Comment by openSISAdmin** [comment]
This is fixed and code committed, please check.
