### ISSUE TITLE
Data import tool gets errors when extra column is not mapped

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#72]
If there is an extra column in the spreadsheet the import tool fails with the following.

![data-import-extra-column](https://user-images.githubusercontent.com/1091769/60859835-0b379000-a268-11e9-8014-5452cc9e2f33.png)

I can provide excel spreadsheet if you can't reproduce

**Comment by openSISAdmin** [comment]
This is fixed
