### ISSUE TITLE
Data import tool importing duplicate staff

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#73]
The tool does not correctly handle duplicated. I can provide the file used for this import.

This is what happens after loading more then one time the spreadsheet I can provide.

![dup-staff1](https://user-images.githubusercontent.com/1091769/60859390-8ef07d00-a266-11e9-8f9a-5140a403e1e4.png)

And then in the system we observe an increasing number of exact same teachers like below.

![dup-staff2](https://user-images.githubusercontent.com/1091769/60859998-b7797680-a268-11e9-8c84-2d2a29c706fb.png)

**Comment by openSISAdmin** [comment]
Resolved
