### ISSUE TITLE
Course period not saving in some circumstances

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#74]
To reproduce the following case you may need a SQL dump of the data we use. I will provide in an email.

The current schedule looks like follows

![Current Schedule](https://user-images.githubusercontent.com/1091769/60931602-34aaf700-a30e-11e9-9c2c-8c4dd901cee6.PNG)

When trying to add the following course period with no classroom, teacher or period conflicts. The Primary Teacher to try here is Nabobo Viliam.

![Create a period BEFORE Saving](https://user-images.githubusercontent.com/1091769/60931638-691eb300-a30e-11e9-80a3-1bf24ba1d107.PNG)

The room, period and meeting days are not saved as shown below.

![Create a period AFTER Saving](https://user-images.githubusercontent.com/1091769/60931673-8f445300-a30e-11e9-9179-fa298a2a0037.PNG)

And then new course period is not shown in the course catalogue after either.

GH

**Comment by openSISAdmin** [comment]
You must save the course period with Room, Period and Meeting days. Otherwise, the course period will not save. There is browser side validation for that. If someone is bypassing the browser validation, then it will not show in the CP list.

**Comment by ghachey** [comment]
We save with Room, Period and Meeting days, of course. The fact is, sometime it does not save and there is no useful message back to the user. For example, I have seen one time that a teacher was already in a period but when trying to save it just did not show a useful message to user saying the teacher is already teaching i that period. We have many course periods created which worked. But this one is not working. I sent a sql dump with the data to try it. Login with user ucagi, Marshall Islands Upper Bound School, and check the full course catalogue. I will provide more instructions also soon.

**Comment by ghachey** [comment]
Also please try to reproduce the above steps in the issue description using the dump sql file I sent. Again, Login with user ucagi, Marshall Islands Upper Bound School, and check the full course catalogue. Then try creating the course period as above with Primary Teacher Nabobo Viliam. If this does not help I will provide another sql dump and more clear instructions to reproduce. There are at least 1-2 issues to fix here.

**Comment by ghachey** [comment]
For example, for teacher Nabobo Viliam the schedule is below.

![teacher schedule](https://user-images.githubusercontent.com/1091769/61010124-279f0e00-a3c9-11e9-8c68-204569abd36a.png)

You see the teacher should be available for Period 2. Yet it can not be added to the course period for MLA.9A. Try it with the user I said in this issue and school in this issue and the SQL dump I sent you.

**Comment by openSISAdmin** [comment]
Resolved
