### ISSUE TITLE
Take Attendance Page Not Matching Attendance Chart Page

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#76]
Login with teacher kosbome

See some of the attendance as marked below and saved.

![Take Attendace Page](https://user-images.githubusercontent.com/1091769/61010284-c3307e80-a3c9-11e9-8a4e-42a6200b0f3b.png)

Yet report shows all present when many students were assigned with absent codes.

![Attendance Chart](https://user-images.githubusercontent.com/1091769/61010779-d04e6d00-a3cb-11e9-9cb4-acedd82d415a.png)

**Comment by openSISAdmin** [comment]
The attendance chart is generated based on full day and half day minutes that are set in the School Setup->School->System Preference

![image](https://user-images.githubusercontent.com/7434280/61082968-9778bd00-a3f8-11e9-8a17-28272f13b5e5.png)

Make sure the values are set in there.

Basic guideline: If a school takes attendance once a day for one period which is 50 minutes long, then put 50 as the full-day minutes.

If a school takes attendance every period and a student has to be present for 6 periods each 50 minutes long, then set the full-day minutes to 300 and a half day to 150.

Unless a student is present for all the 6 periods the system will show Half day present or Absent.

**Comment by ghachey** [comment]
Thank you. This works.
