### ISSUE TITLE
Scheduling Report Print Schedule issue

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#79]
Login as rrilometo and school Majuro Middle School. Try to print schedule (Scheduling -> Reports -> Print Schedule). Select all students and see the following.

<img width="1649" alt="Screen Shot 2019-07-11 at 1 48 13 PM" src="https://user-images.githubusercontent.com/1091769/61016178-dc91f480-a3e2-11e9-99fd-1dd1f9d9f052.png">

Execute and get the following.

<img width="1648" alt="Screen Shot 2019-07-11 at 1 48 24 PM" src="https://user-images.githubusercontent.com/1091769/61016187-e4ea2f80-a3e2-11e9-8f81-c4dcf1205d8e.png">

And re-clicking on the select all should remove all student yet they remain all selected as shown below.

<img width="1655" alt="Screen Shot 2019-07-11 at 1 51 45 PM" src="https://user-images.githubusercontent.com/1091769/61016243-0d722980-a3e3-11e9-9a42-68a767ccca68.png">

**Comment by openSISAdmin** [comment]
Resolved
