### ISSUE TITLE
Missing execute command to get final grade report

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#80]
As shown below.

![Final Grades Report WITHOUT execute command](https://user-images.githubusercontent.com/1091769/61016760-e61c5c00-a3e4-11e9-9fad-e095ba7e8b42.png)

To reproduce login as teacher kosborne and try to Grades -> Reports -> Final Grade and try to execute a final grade report.

**Comment by openSISAdmin** [comment]
You have to clear browser cache ....the generate grade list is in the lower right-hand corner

![image](https://user-images.githubusercontent.com/7434280/61063995-f45f7d80-a3ce-11e9-904c-718008c4c56c.png)

**Comment by ghachey** [comment]
I tried as suggested and it does not work. I gave the steps to reproduce. You can also try login in the training test system at https://misis.pss.edu.mh/training/index.php and login with teacher kosborne and try to Grades -> Reports -> Final Grade and try to execute a final grade report. There is no button like on your image.

**Comment by ghachey** [comment]
This needs to be re-opened

**Comment by openSISAdmin** [comment]
Cannot recreate

**Comment by ghachey** [comment]
Have you tried login in the one I tell you?

**Comment by openSISAdmin** [comment]
Using your database, we were able to recreate the error. This could be a data issue. Has been escalated to a lead developer.

**Comment by ghachey** [comment]
Many thanks. Here also might be related when trying to see "Grades -> Reports -> Final Grades" with teacher alang with the current https://misis.pss.edu.mh/training/index.php there is missing execute button.

<img width="1646" alt="Screen Shot 2019-07-12 at 2 03 23 PM" src="https://user-images.githubusercontent.com/1091769/61097094-06641d80-a4ae-11e9-99c7-0480308b3c8a.png">

Let me know if you need the SQL dump for the latest of this training system

**Comment by openSISAdmin** [comment]
Fixed

![image](https://user-images.githubusercontent.com/7434280/61157448-30283f00-a4c4-11e9-8557-23f4fb002e28.png)

**Comment by openSISAdmin** [comment]
Will right justify the button and close it.

**Comment by openSISAdmin** [comment]
This one is fixed also, but waiting for your database backup to check against it before closing the ticket.

**Comment by ghachey** [comment]
The button is now showing and report seems to execute with latest upgrade.
