### ISSUE TITLE
Not selecting a students for final grade report

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#81]
Login kosborne. Try to Grades > Reports > Final Grades

Upon selecting the grade level and section the next page is displayed. When the column header box is checked, one box is NOT selected but the rest are.

![checking issue](https://user-images.githubusercontent.com/1091769/61016963-a9049980-a3e5-11e9-8031-4b3cf3b3481c.png)

**Comment by openSISAdmin** [comment]
Resolved

**Comment by openSISAdmin** [comment]
The same issue is occurring for the Progress Report.

Go to Grades-Gradebook-Progress Report and one student record does not get selected.

**Comment by openSISAdmin** [comment]
This issue is fixed and code committed.
