### ISSUE TITLE
Generating transcript error

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#82]
Login as admin or ucagi. Use Marshall Islands Upper Bound School and Go to Grades > Trancripts

Upon selecting the grade level, section and term (Q1) the next page is displayed. Students are selected then report is run and error message appears.

![Transcript_Error Message](https://user-images.githubusercontent.com/1091769/61017393-1e249e80-a3e7-11e9-9378-0792d9e28d54.png)

**Comment by openSISAdmin** [comment]
Resolved
