### ISSUE TITLE
Mismatch in scheduled students number

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#85]
See first figure below. All seats are opened.

<img width="1649" alt="Screen Shot 2019-07-12 at 10 29 07 AM" src="https://user-images.githubusercontent.com/1091769/61089682-06552500-a490-11e9-838d-e779ef5eea81.png">

But when clicking on the homeroom attendance grade 1 course period you see there are students.

<img width="1650" alt="Screen Shot 2019-07-12 at 10 29 20 AM" src="https://user-images.githubusercontent.com/1091769/61089701-1d941280-a490-11e9-94f6-7236d77fad5d.png">

**Comment by openSISAdmin** [comment]
Fixed
