### ISSUE TITLE
Why no GPA showing

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#87]
Why is there no GPA showing here? Many users see this.

<img width="1651" alt="Screen Shot 2019-07-12 at 2 39 44 PM" src="https://user-images.githubusercontent.com/1091769/61098412-fac72580-a4b2-11e9-8810-2f22692263b9.png">

**Comment by openSISAdmin** [comment]
Resolved

**Comment by ghachey** [comment]
I don't see this resolved. Is it a missing store proc or function?

**Comment by ghachey** [comment]
I have loaded the stored procs and functions and I still see this problem. I will send a sql dump of what I am currently using.

**Comment by openSISAdmin** [comment]
Reopened as per Ghislain's request

**Comment by openSISAdmin** [comment]
Looks like the GPA is not showing because of those course periods do not have Credit hours filled in. System won't allow entering after the course has been graded. You can do it from the database.
