### ISSUE TITLE
Missing home page summary

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#89]
Some users are asking the home page is not there, the one showing the progress of the setup of the school. This could be by design once the schools setup is complete?!

![missing-home-page](https://user-images.githubusercontent.com/1091769/61099938-39abaa00-a4b8-11e9-8e17-c2cc03fc075d.png)

**Comment by openSISAdmin** [comment]
When the school setup is complete the home page setup items are cleared out. If you want to show some text, go to School setup ->Portal notes and enter the required text to display.
