### ISSUE TITLE
Schedule type enter by calendar days is not working

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#9]
![screen shot 2018-06-15 at 9 34 59 am](https://user-images.githubusercontent.com/1091769/41441693-75b594ac-707f-11e8-9c8d-8893cfeed643.png)

Not urgent, but a message saying this feature will be coming soon would be useful.

**Comment by openSISAdmin** [comment]
Unable to reproduce. Make sure you clicked the save button for the calendar to appear. Internal tests show that this feature works well.
