### ISSUE TITLE
Can't deselect fields from advanced report

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#90]
Login as teacher (e.g. kosborne) and go to "Students -> Reports -> Advanced Reports". After selecting the relevant field/student, when fields are selected its ok BUT can not be de-selected before the report is run.

![De-Select field issue](https://user-images.githubusercontent.com/1091769/61190212-e66e6d00-a6ec-11e9-99fc-866522f86315.PNG)

**Comment by openSISAdmin** [comment]
That is by design from the very beginning. Not a defect.
