### ISSUE TITLE
Excused and Unexcused not adding up in Student Report Card

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#91]
Login as a teacher (e.g. kosborne). Within the report card, unexcused (6 count) and excused (3 count) absences not adding up with column labelled - Abx YTD/MP (8 count).

![Excused and Unexcused not adding up correctly](https://user-images.githubusercontent.com/1091769/61190222-32b9ad00-a6ed-11e9-80ad-0e74773ca8b2.PNG)

**Comment by openSISAdmin** [comment]
Fixed
