### ISSUE TITLE
Users confused by gradebook progress report

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#92]
See figure below. Here are some comments:

- Can the ordering follow the assignment types? Right now they seems a little all over the place and not nicely grouped by assignment types in the table

- The users were not expecting to see the full assignment type assigned to each assignment inside a particular assignment type. For example below in the red rectangle. Those are classwork. Users assignment 30% for all "Classwork" yet the progress report makes it look like every assignment inside "Classwork" is 30%.  The actual final results seem to be correctly calculated. It is just how each assignment is shown to be the whole percentage of it's respective assignment type that is creating lots of confusion. Could this be better presented to the user.

<img width="1652" alt="Screen Shot 2019-07-15 at 9 47 40 AM" src="https://user-images.githubusercontent.com/1091769/61190348-f71fe280-a6ee-11e9-981d-591f3a6a0364.png">

**Comment by openSISAdmin** [comment]
We should move the Weight (%) column to the left of the Assignment and it will become easier to read.
We will see if the assignments can be grouped by assignment type.

**Comment by openSISAdmin** [comment]
The Weight column was shifted to the left of the Assignment column.

![image](https://user-images.githubusercontent.com/7434280/62801682-440b9480-bab4-11e9-8d0a-4a8fce9d2f6a.png)
