### ISSUE TITLE
Emergency Contact lookup not working

### ISSUE THREAD

**Issue by brudosm** [OS4ED/openSIS-Responsive-Design#93]
Version 7.2 - Using the lookup functionality for the primary or secondary emergency contact doesn't seem to work consistently. Sometimes the search works and sometimes it returns nothing. Sometimes when I select the contact after searching it populates the form but most of the time it doesn't. Let me know what else I can provide to help.

**Comment by openSISAdmin** [comment]
Try to refresh your build with the latest code from the repository.....we made many updates since the last release and working towards a new release.

If you still get this error, create a video and upload it to screencast and share the link so that we can see the cases.

Thnks

**Comment by brudosm** [comment]
Was not able to successfully upgrade and re-test this issue.

**Comment by openSISAdmin** [comment]
You were NOT able to or able to?
