### ISSUE TITLE
Bulk loaded teachers login to nothing

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#95]
When bulk loading the teachers they loading to nothing even if they are assigned active to the default first school created. The user see this.

<img width="1372" alt="Screen Shot 2019-08-13 at 12 15 52 PM" src="https://user-images.githubusercontent.com/1091769/62908581-72df7e80-bdc4-11e9-8203-7fcc96c1f7c2.png">

If a super administrator does to that user and unselect the default school, save and then re-select the default school then the user can login properly with the full menu to that school.

<img width="1369" alt="Screen Shot 2019-08-13 at 12 16 30 PM" src="https://user-images.githubusercontent.com/1091769/62908604-95719780-bdc4-11e9-9593-5550e38cba82.png">

**Comment by openSISAdmin** [comment]
This issue is fixed. For the existing teachers who are already in the system, you have to uncheck and check. But the new staff should be fine.
