### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#96]
![Screen Shot 2019-08-13 at 3 24 19 PM](https://user-images.githubusercontent.com/1091769/62915002-8d265600-bdde-11e9-856f-0423d0cd4ea4.png)

**Comment by openSISAdmin** [comment]
What are the steps to reproduce this error?

**Comment by ghachey** [comment]
un-select all the schools for a user and try to login

**Comment by ghachey** [comment]
This is actually a duplicate of issue #96 I think

**Comment by openSISAdmin** [comment]
Staff needs to be associated with one school at least. When you are adding a staff sitting in that school, that staff will have an association with the school. That staff might not have openSIS portal access. 

To correctly test this use case, select any school and add one staff and do not provide openSIS access. If the administrator can see that staff's full record, then it is all good.

**Comment by ghachey** [comment]
Yes that is fine. But in the case where a staff is made to not have a selected school (which *is* allowed by the UI) then there should be a way to re-enter the staff and select a school. Currently this does not work so we have a UI that allows a user to enter themselves in  a situation where a SQL error results without any mean to sort the issue except fixing the data directly in the DB which is what I did. In good UI this does not happen and could be improved as a bit discussed in #97. Personally I still see some improvements that could be made here.
