### ISSUE TITLE
No show staff with no current_school_id

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#97]
Currently the system does not show staff without a current_school_id. Trying to list those staff with following search they do not show.

<img width="1371" alt="Screen Shot 2019-08-13 at 5 01 19 PM" src="https://user-images.githubusercontent.com/1091769/62919142-7fc49800-bded-11e9-94c1-94e89e0d4653.png">

But I know they are in the system as I see it in the data. This happens when the user had all their schools unselected. And they they can no loger login with an SQL error like below.

<img width="1147" alt="Screen Shot 2019-08-13 at 5 11 23 PM" src="https://user-images.githubusercontent.com/1091769/62919231-c4503380-bded-11e9-8216-c902927c97ee.png">

Ideally we could see all staff from a super administrator when doing the search above and re-select the school for them to be active for. Currently I need to go directly in the sql database and fix it there.

**Comment by openSISAdmin** [comment]
Please see the comments on #96
