### ISSUE TITLE
Course Period Choose Schedule Type Note Saving

### ISSUE THREAD

**Issue by ghachey** [OS4ED/openSIS-Responsive-Design#99]
For one teacher who is available in a room that is available and a period that is available the Schedule Type is not saving.

![Screen Shot 2019-08-16 at 11 33 10 AM](https://user-images.githubusercontent.com/1091769/63135452-abc46100-c019-11e9-990d-de5d4344a67f.png)

To repeat restore the dump of the SQL data I will send by email. Then login as super admin (I create one for Bob and will send details by email). Select the school Sanskrit Elementary School. Try to open the course period Social Studies -> SS1 - Social Studies (G1) -> SS-G1 - Madlina Timothy and try to complete the Schedule Type with

Classroom 3, Period 3, Every day of week.

There is no error message on save and the schedule type is not saved and course period not in the catalogue. This is the case in at least 2 other ones.

**Comment by openSISAdmin** [comment]
Fixed
